version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: quizzer_mysql
    networks:
      default:
        ipv4_address: 192.168.2.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: the_quizzer
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quizzer_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      default:
        ipv4_address: 192.168.2.4
    ports:
      - 8183:80

  web:
    build: ./.docker
    container_name: quizzer_web
    networks:
      default:
        ipv4_address: 192.168.2.2
    volumes:
      - ./:/var/www/html/
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:8080"
    depends_on:
      - "mysql"
  develop_init:
    build: ./.docker
    container_name: quizzer_develop_init
    volumes:
      - ./:/var/www/html/
      - ./.docker/init_symfony.sh:/usr/local/bin/init_symfony.sh
    depends_on:
      - "mysql"
      - "web"
    command: "init_symfony.sh"
    
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
