version: "3"
services:
  web:
    build: ./.docker
    networks:
      default:
        ipv4_address: 192.168.2.2
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:8080"

  mysql:
    image: mysql:5.7
    networks:
      default:
        ipv4_address: 192.168.2.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: the_quizzer
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "9906:3306"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24