name: Docker compose workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-20.04, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Docker compose up
        run: docker-compose up -d --build
      - name: Install dependencies via composer
        run: docker exec quizzer_web composer install
      - name: Run PHPUNIT
        run: docker exec quizzer_web ./vendor/bin/phpunit
      - name: Run PHPSTAN
        run: docker exec quizzer_web ./vendor/bin/phpstan analyse src --level 5
      - name: Deploy to live
          uses: distributhor/workflow-webhook@v1
          env:
            webhook_url: ${{ secrets.WEBHOOK_URL }}
            webhook_secret: ${{ secrets.WEBHOOK_SECRET }}