name: Docker compose workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker compose up
        run: docker-compose up -d
      - name: Connect to docker server bash
        run: docker exec -it quizzer_web bash
      - name: Run PHPUNIT
        run: ./vendor/bin/phpunit
      - name: Run PHPSTAN
        run: ./vendor/bin/phpstan analyse src --level 5
